version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "443:8000"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./dev_keys:/etc/nginx/dev_keys
    depends_on:
      - web
  rabbit:
    image: rabbitmq
    ports:
      - "5672:5672"
  redis:
    image: redis
    ports:
      - "6379:6379"
  web:
    build: .
    entrypoint: /app/docker-entrypoint.sh
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DWOLLA_KEY=${DWOLLA_KEY}
      - DWOLLA_SECRET=${DWOLLA_SECRET}
      - DWOLLA_FUNDING_SOURCE_KEY=${DWOLLA_FUNDING_SOURCE_KEY}
      - AUTHORIZE_KEY=${AUTHORIZE_KEY}
      - AUTHORIZE_SECRET=${AUTHORIZE_SECRET}
      - GR_CAPTCHA_SECRET_KEY=${GR_CAPTCHA_SECRET_KEY}
      - GR_CAPTCHA_PUBLIC_KEY=${GR_CAPTCHA_PUBLIC_KEY}
      - TELEGRAM_BOT_KEY=${TELEGRAM_BOT_KEY}
      - HTTPS=1
      - TELEGRAM_BOT_USERNAME=ArtconomyDevBot
      - CELERY_ALWAYS_EAGER=1
      - CELERY_BROKER_CONNECTION_RETRY=1
      - EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
      - OTP_TOTP_ISSUER=Artconomy Dev
      - SERVICE_PERCENTAGE_FEE=5
      - PREMIUM_PERCENTAGE_BONUS=3
      - LANDSCAPE_PRICE=8
      - ENV_NAME=dev
      - CHANNELS_HOST=redis
      - STRIPE_PUBLIC_KEY=pk_test_5lB4V6MnoGYhtEuL0iEVa7Xu00oT23zRr5
      - STRIPE_KEY=sk_test_tgpnmm2xxdzgMkv5KeZ3LT0200clEdHF8X
      - DEFAULT_CARD_PROCESSOR=authorize
    command: /usr/bin/python3.8 manage.py runserver 0.0.0.0:8002
    ports:
      - "8001:8001"
      - "8002:8002"
    depends_on:
      - db
      - rabbit
      - redis
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
