---
- name: Install postfix
  apt:
    name:
      - postfix
      - opendkim
      - opendkim-tools
    state: present

- name: Configure Postfix
  template:
    src: "templates/main.cf"
    dest: "/etc/postfix/main.cf"
  notify:
    - restart postfix

- name: Ensure header checks configuration file
  template:
    src: "templates/header_checks"
    dest: "/etc/postfix/header_checks"
  notify:
    - postmap
    - restart postfix

- name: Add dkim key
  copy:
    src: "keys/{{env_prefix}}/mail/mail.key"
    dest: /etc/mail/mail.key
    mode: 0600
    owner: opendkim
  notify:
    - restart opendkim

- name: Configure OpenDKIM
  template:
    src: "templates/opendkim.conf"
    dest: "/etc/opendkim.conf"
  notify:
    - restart opendkim
    - restart postfix


- name: Ensure OpenDKIM is running
  service:
    name: opendkim
    enabled: yes
    state: started

- name: Ensure Postfix is running
  service:
    name: postfix
    enabled: yes
    state: started
