- hostname:
    name: "{{ inventory_hostname.split('.')[0] }}"

- name: Add hostname to hosts file
  lineinfile:
    line: "127.0.0.1 {{ inventory_hostname }}"
    path: /etc/hosts

- name: Add shortname to hosts file
  lineinfile:
    line: "127.0.0.1 {{ inventory_hostname.split('.')[0] }}"
    path: /etc/hosts

- name: Add redis PPA
  apt_repository:
    repo: ppa:chris-lea/redis-server


- name: Update Packages
  apt:
    cache_valid_time: 8400
    update_cache: yes
    upgrade: yes
  when: perform_upgrades|bool

- name: Install utils
  apt:
    name:
      - screen
      - vim
      - build-essential
      - unattended-upgrades
    state: present

- name: Enable overcommit memory
  lineinfile:
    destfile: /etc/sysctl.conf
    line: vm.overcommit_memory=1
  notify:
    reload_sysctl

- name: Disable transparent hugepages
  copy:
    src: files/rc.local
    dest: /etc/rc.local
    mode: '0777'
  notify:
    force_disable_hugepages