---
- name: reload systemd
  shell: "systemctl daemon-reload"
  args:
    executable: "/bin/bash"

- name: migrator
  become: yes
  become_user: "{{ env_prefix }}"
  shell: "source ~/.profile && source ~/bin/activate && cd ~/artconomy && yes no | ./manage.py migrate && ./manage.py createinitialrevisions && echo '{{ migrations_status.digest }}' > ~/.migrations_hash"
  args:
    executable: "/bin/bash"

- name: collect static assets
  become: yes
  become_user: "{{ env_prefix }}"
  shell: "source ~/.profile && source ~/bin/activate && cd ~/artconomy  && npm run build && ./manage.py collectstatic -v0 --noinput && cp webpack-stats{,-saved}.json && echo '{{ static_status.digest }}' > {{ home }}/.static_hash && git rev-parse --short HEAD > ~/artconomy/.static_hash_head"
  args:
    executable: "/bin/bash"
  environment:
    # Memory leak somewhere? This is enough for this task for now.
    NODE_OPTIONS: --max-old-space-size=6144
  register: result
  notify:
    - rebuild pinterest

- name: restart uwsgi
  service: name=uwsgi state=restarted

- name: restart daphne
  service: name=artconomy-daphne state=restarted

- name: set tg webhook
  become: yes
  become_user: "{{ env_prefix }}"
  shell: "source ~/.profile && source ~/bin/activate && cd ~/artconomy && ./manage.py set_webhook"
  args:
    executable: "/bin/bash"

- name: rebuild pinterest
  become: yes
  become_user: "{{ env_prefix }}"
  shell: "source ~/.profile && source ~/bin/activate && cd ~/artconomy  && mkdir -p ~/artconomy/public/dist/csv/ && ./manage.py pinterest_catalog > ~/artconomy/public/dist/csv/pinterest.csv"
  args:
    executable: "/bin/bash"
  tags:
    # Disabling since Pinterest doesn't support our catalog.
    - never